[package]
name = "chimera-compiler-jit"
version.workspace = true
edition.workspace = true
description = "Adaptive Wasm tier selection / retro-scaling for Chimera"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
readme = "README.md"

[dependencies]
serde = { version = "1", features = ["derive"] }
