#!/usr/bin/env bash
# Sync README.md "Crates.io packages" section from crates.io LIVE status.
# Markers: <!-- CRATES-IO-START --> ... <!-- CRATES-IO-END -->
#
# Usage:
#   ./scripts/sync-crates-readme.sh              # update only if all crates LIVE
#   ./scripts/sync-crates-readme.sh --force      # write section even if some missing
#   ./scripts/sync-crates-readme.sh --check-only # print LIVE/MISS; exit 0 only if all LIVE
#   ./scripts/sync-crates-readme.sh --require-all
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FORCE=0
CHECK_ONLY=0
REQUIRE_ALL=0
README_PATH="README.md"
VERSION=""

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --check-only) CHECK_ONLY=1 ;;
    --require-all) REQUIRE_ALL=1 ;;
    --readme=*) README_PATH="${arg#*=}" ;;
    --version=*) VERSION="${arg#*=}" ;;
    -h|--help)
      echo "Usage: $0 [--force|--check-only|--require-all]"
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

# Keep in sync with scripts/publish-crates.sh / publish-crates.ps1
CRATES=(
  chimera-nano-kernel
  chimera-transport-quic
  chimera-rbac-auth
  chimera-compiler-jit
  chimera-compliance-tee
  chimera-inference-engine
  chimera-policy-engine
  chimera-consensus-dag
  chimera-audit-ledger
  chimera-storage-cas
  chimera-network-bridge
  chimera-crypto-quantum
  chimera-nexus
  chimera-dht-routing
  chimera-agent-swarm
  chimera-memory-fabric
  chimera-telemetry-otel
  chimera-wasm-runtime
  chimera-fuser-mount
  chimera-boot
  chimera-mesh
  chimera-usb-daemon
  chimeractl
)

UA="chimera-sync-crates-readme (github.com/theworker02/chimera)"
START_MARKER="<!-- CRATES-IO-START -->"
END_MARKER="<!-- CRATES-IO-END -->"

if [[ -z "$VERSION" ]]; then
  VERSION="$(grep -E '^\s*version\s*=\s*"' Cargo.toml | head -n1 | sed -E 's/.*"([^"]+)".*/\1/')"
fi

LIVE=()
MISSING=()

crate_live() {
  local name="$1" ver="$2"
  local code
  code="$(curl -sS -o /dev/null -w '%{http_code}' \
    -H "User-Agent: $UA" \
    --max-time 20 \
    "https://crates.io/api/v1/crates/${name}/${ver}" || true)"
  [[ "$code" == "200" ]]
}

for crate in "${CRATES[@]}"; do
  sleep 1.5
  if crate_live "$crate" "$VERSION"; then
    LIVE+=("$crate")
    echo "LIVE  ${crate}@${VERSION}"
  else
    MISSING+=("$crate")
    echo "MISS  ${crate}@${VERSION}"
  fi
done

echo "----"
echo "LIVE: ${#LIVE[@]}/${#CRATES[@]} (target ${VERSION})"
if ((${#MISSING[@]} > 0)); then
  echo "MISSING: ${MISSING[*]}"
fi

if ((CHECK_ONLY)); then
  ((${#MISSING[@]} == 0)) && exit 0
  exit 1
fi

must_have_all=0
if ((REQUIRE_ALL)) || ((FORCE == 0)); then
  must_have_all=1
fi
if ((must_have_all)) && ((${#MISSING[@]} > 0)); then
  echo "Not all crates are LIVE; refusing to rewrite README (pass --force to override)."
  exit 2
fi

is_live() {
  local needle="$1" c
  for c in "${LIVE[@]}"; do
    [[ "$c" == "$needle" ]] && return 0
  done
  return 1
}

emit_group() {
  local title="$1"; shift
  echo "### $title"
  echo
  local name
  for name in "$@"; do
    if is_live "$name"; then
      echo "- [\`$name\`](https://crates.io/crates/$name)"
    else
      echo "- \`$name\` _(pending publish)_"
    fi
  done
  echo
}

SECTION_FILE="$(mktemp)"
{
  echo "$START_MARKER"
  echo "## Crates.io packages"
  echo
  echo "All publishable workspace crates at **v${VERSION}** on [crates.io](https://crates.io):"
  echo
  emit_group "Foundation" \
    chimera-nano-kernel chimera-crypto-quantum chimera-transport-quic chimera-dht-routing
  emit_group "Execution" \
    chimera-wasm-runtime chimera-memory-fabric chimera-storage-cas chimera-fuser-mount \
    chimera-consensus-dag chimera-network-bridge chimera-compiler-jit
  emit_group "Intelligence" \
    chimera-nexus chimera-agent-swarm chimera-inference-engine chimera-telemetry-otel
  emit_group "Security" \
    chimera-rbac-auth chimera-compliance-tee chimera-policy-engine chimera-audit-ledger
  emit_group "Tooling" \
    chimeractl chimera-boot chimera-usb-daemon
  emit_group "Umbrella" \
    chimera-mesh
  echo "Regenerated by \`scripts/sync-crates-readme.sh\` (markers \`$START_MARKER\` / \`$END_MARKER\`)."
  echo "$END_MARKER"
} > "$SECTION_FILE"

if grep -qF "$START_MARKER" "$README_PATH" && grep -qF "$END_MARKER" "$README_PATH"; then
  # Replace existing marked block (portable awk).
  awk -v start="$START_MARKER" -v end="$END_MARKER" -v secfile="$SECTION_FILE" '
    BEGIN { while ((getline line < secfile) > 0) sec = sec line ORS; close(secfile) }
    $0 == start { print sec; skip=1; next }
    $0 == end { skip=0; next }
    !skip { print }
  ' "$README_PATH" > "${README_PATH}.tmp"
  mv "${README_PATH}.tmp" "$README_PATH"
else
  if grep -qF "## Phase 14 — Chimera Boot-Sovereign" "$README_PATH"; then
    awk -v secfile="$SECTION_FILE" '
      BEGIN { while ((getline line < secfile) > 0) sec = sec line ORS; close(secfile) }
      $0 == "## Phase 14 — Chimera Boot-Sovereign" { printf "%s\n", sec }
      { print }
    ' "$README_PATH" > "${README_PATH}.tmp"
    mv "${README_PATH}.tmp" "$README_PATH"
  else
    {
      cat "$README_PATH"
      echo
      cat "$SECTION_FILE"
    } > "${README_PATH}.tmp"
    mv "${README_PATH}.tmp" "$README_PATH"
  fi
fi

rm -f "$SECTION_FILE"
echo "Updated ${README_PATH} crates.io section (${#LIVE[@]}/${#CRATES[@]} LIVE)."
