# Sync README.md "Crates.io packages" section from crates.io LIVE status.
# Markers: <!-- CRATES-IO-START --> ... <!-- CRATES-IO-END -->
#
# Usage:
#   .\scripts\sync-crates-readme.ps1              # update only if all crates LIVE
#   .\scripts\sync-crates-readme.ps1 -Force       # write section even if some missing
#   .\scripts\sync-crates-readme.ps1 -CheckOnly   # print LIVE/MISS; exit 0 only if all LIVE
#   .\scripts\sync-crates-readme.ps1 -RequireAll  # fail if any crate missing (default for CI write)
param(
    [switch]$Force,
    [switch]$CheckOnly,
    [switch]$RequireAll,
    [string]$ReadmePath = "README.md",
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"
Set-Location (Split-Path $PSScriptRoot -Parent)

# Keep in sync with scripts/publish-crates.ps1 / publish-crates.sh
$Crates = @(
    "chimera-nano-kernel",
    "chimera-transport-quic",
    "chimera-rbac-auth",
    "chimera-compiler-jit",
    "chimera-compliance-tee",
    "chimera-inference-engine",
    "chimera-policy-engine",
    "chimera-consensus-dag",
    "chimera-audit-ledger",
    "chimera-storage-cas",
    "chimera-network-bridge",
    "chimera-crypto-quantum",
    "chimera-nexus",
    "chimera-dht-routing",
    "chimera-agent-swarm",
    "chimera-memory-fabric",
    "chimera-telemetry-otel",
    "chimera-wasm-runtime",
    "chimera-fuser-mount",
    "chimera-boot",
    "chimera-mesh",
    "chimera-usb-daemon",
    "chimeractl"
)

# Sensible README grouping (not publish order).
$Groups = [ordered]@{
    "Foundation" = @(
        "chimera-nano-kernel",
        "chimera-crypto-quantum",
        "chimera-transport-quic",
        "chimera-dht-routing"
    )
    "Execution" = @(
        "chimera-wasm-runtime",
        "chimera-memory-fabric",
        "chimera-storage-cas",
        "chimera-fuser-mount",
        "chimera-consensus-dag",
        "chimera-network-bridge",
        "chimera-compiler-jit"
    )
    "Intelligence" = @(
        "chimera-nexus",
        "chimera-agent-swarm",
        "chimera-inference-engine",
        "chimera-telemetry-otel"
    )
    "Security" = @(
        "chimera-rbac-auth",
        "chimera-compliance-tee",
        "chimera-policy-engine",
        "chimera-audit-ledger"
    )
    "Tooling" = @(
        "chimeractl",
        "chimera-boot",
        "chimera-usb-daemon"
    )
    "Umbrella" = @(
        "chimera-mesh"
    )
}

$Ua = "chimera-sync-crates-readme (github.com/theworker02/chimera)"
$StartMarker = "<!-- CRATES-IO-START -->"
$EndMarker = "<!-- CRATES-IO-END -->"

if (-not $Version) {
    $Version = (
        Select-String -Path Cargo.toml -Pattern '^\s*version\s*=\s*"([^"]+)"' |
        Select-Object -First 1
    ).Matches[0].Groups[1].Value
}

function Test-CrateLive([string]$Name, [string]$Ver) {
    $url = "https://crates.io/api/v1/crates/$Name/$Ver"
    try {
        Invoke-RestMethod -Uri $url -Headers @{ "User-Agent" = $Ua } -TimeoutSec 20 | Out-Null
        return $true
    } catch {
        return $false
    }
}

$live = [System.Collections.Generic.HashSet[string]]::new()
$missing = [System.Collections.Generic.List[string]]::new()

foreach ($crate in $Crates) {
    Start-Sleep -Milliseconds 1500
    if (Test-CrateLive $crate $Version) {
        [void]$live.Add($crate)
        Write-Host "LIVE  $crate@$Version"
    } else {
        $missing.Add($crate)
        Write-Host "MISS  $crate@$Version"
    }
}

Write-Host "----"
Write-Host "LIVE: $($live.Count)/$($Crates.Count) (target $Version)"
if ($missing.Count -gt 0) {
    Write-Host "MISSING: $($missing -join ', ')"
}

if ($CheckOnly) {
    if ($missing.Count -eq 0) { exit 0 }
    exit 1
}

$mustHaveAll = $RequireAll -or (-not $Force)
if ($mustHaveAll -and $missing.Count -gt 0) {
    Write-Host "Not all crates are LIVE; refusing to rewrite README (pass -Force to override)."
    exit 2
}

function New-CratesSection([string]$Ver, $LiveSet) {
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine($StartMarker)
    [void]$sb.AppendLine("## Crates.io packages")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("All publishable workspace crates at **v$Ver** on [crates.io](https://crates.io):")
    [void]$sb.AppendLine("")
    foreach ($groupName in $Groups.Keys) {
        [void]$sb.AppendLine("### $groupName")
        [void]$sb.AppendLine("")
        foreach ($name in $Groups[$groupName]) {
            $href = "https://crates.io/crates/$name"
            if ($LiveSet.Contains($name)) {
                [void]$sb.AppendLine("- [`$name`]($href)")
            } else {
                [void]$sb.AppendLine("- `$name` _(pending publish)_")
            }
        }
        [void]$sb.AppendLine("")
    }
    [void]$sb.AppendLine("Regenerated by ``scripts/sync-crates-readme.ps1`` (markers ``$StartMarker`` / ``$EndMarker``).")
    [void]$sb.AppendLine($EndMarker)
    return $sb.ToString().TrimEnd() + "`n"
}

$section = New-CratesSection $Version $live
$readmeFull = Resolve-Path $ReadmePath
$text = Get-Content -Raw -Path $readmeFull

if ($text.Contains($StartMarker) -and $text.Contains($EndMarker)) {
    $pattern = [regex]::Escape($StartMarker) + "[\s\S]*?" + [regex]::Escape($EndMarker)
    $updated = [regex]::Replace($text, $pattern, { param($m) $section.TrimEnd() }, 1)
} else {
    # Insert after the Install section (before Phase 14), or append if missing.
    # Match Phase 14 heading without relying on Unicode dash encoding.
    if ($text -match '(?m)^## Phase 14 .+ Chimera Boot-Sovereign\s*$') {
        $anchor = $Matches[0]
        $updated = $text.Replace($anchor, ($section + "`n" + $anchor))
    } else {
        $updated = $text.TrimEnd() + "`n`n" + $section
    }
}

if ($updated -eq $text) {
    Write-Host "README already up to date."
    exit 0
}

Set-Content -Path $readmeFull -Value $updated -NoNewline
$liveCount = $live.Count
$totalCount = $Crates.Count
Write-Host "Updated $readmeFull crates.io section ($liveCount/$totalCount LIVE)."
exit 0
